baseurl                = "http://norskkurs.netlify.com"
builddrafts            = false
canonifyurls           = true
contentdir             = "content"
languageCode           = "no-no"
layoutdir              = "layouts"
publishdir             = "public"
theme                  = "cocoa-hugo-theme"
author                 = "Raju Rimal"
title                  = "Raju Rimal"
pygmentsuseclasses     = true
#disqusshortname       = "therimalaya" 
#googleAnalytics       = "UA-123-45"
pluralizelisttitles    = false
ignoreFiles            = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
defaultContentLanguage = "no"

[permalinks]
blog                   = "lekser/:slug/"

[[menu.main]]
name                   = "Lekser"
weight                 = -120
identifier             = "blog"
url                    = "/"

[[menu.main]]
name                   = "Om Meg"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
latestpostscount       = 5                             
i18n_flags             = false                         
author                 = "Raju Rimal"
title                  = "Norsk Kurs"
cachebuster            = true                          
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = "therimalaya@gmail.com"
extracssfiles          = [ "/css/override.css" , "/css/bootstrap.min.css"]       
extrascript            = ["/js/jquery.slim.min.js", "/js/popper.min.js", "/js/bootstrap.min.js"]
faviconfile            = "img/leaf.ico"
github                 = "//github.com/therimalaya"
highlightjs            = true
instagram              = "//instagram.com/therimalaya"
lang                   = "en"
linkedin               = "//linkedin.com/in/therimalaya"
noshowreadtime         = false                         
selfintro              = ""                            
twitter                = "//twitter.com/therimalaya"
# highlightjslanguages = ["go"]                        
# highlightjsStyle     = "darcula"

piwik                  = false                         
# piwik_url            = "//www.example.com/piwik/"    
# piwik_id             = 2                             

avatar                 = "img/profile.jpg" 
# gravatar             = ""                

# The following are DEPRECATED.
gatracker              = "XYZ" 
initials               = "ad"  
